### ISSUE TITLE
Library always returns empty results

### ISSUE THREAD

**Issue by ablanco** [christophe77/formula-one-js#2]
Hi. I'm using this library in one project (a F1 Telegram bot) and it's great, but this last week it has stopped working.

I've been debugging, and I've found this error: `Uncaught Error: unable to verify the first certificate`

![image](https://github.com/christophe77/formula-one-js/assets/535478/4b61aa97-40c5-41ad-b173-f35e13cd916b)

It happens de moment it calls Axios to make a request, it doesn't matter which one.

**Comment by christophe77** [comment]
Thank you for your feedback. I'll check that tonight and I'll let you know.

**Comment by christophe77** [comment]
It's fixed in 1.0.9, let me know if it's ok for you.

**Comment by ablanco** [comment]
Yes, it works now. Thanks!
